name: dcase18

channels:
  - defaults
  - conda-forge

dependencies:
- python=2.7
- numpy=1.15.4
- scipy=1.1.0
- mkl=2017
- mkl-service=1.1.2
- theano=1.0.3
- pygpu=0.7.6
- scikit-learn=0.20.2
- cython=0.29.6
- opencv=3.4.4
- librosa=0.6.3

- pip:
  - munkres==1.0.12
  - scikit-image==0.14.2
  - tqdm==4.31.1
  - setuptools==20.7.0
  - git+https://github.com/Lasagne/Lasagne.git
  - git+https://github.com/CPJKU/madmom.git@v0.16.1
  - opencv_python==3.4.4.19
  - seaborn==0.8
